In [1]:
import os
import pandas as pd

In [5]:
df = pd.read_csv("/Users/siddarvind/Downloads/airports.csv")
df.head()

,code,icao,name,latitude,longitude,elevation,url,time_zone,city_code,country,city,state,county,type
0,AAA,NTGA,Anaa,-17.350665,-145.511120,36,NaN,Pacific/Tahiti,AAA,PF,NaN,NaN,NaN,AP
1,AAB,YARY,Arrabury Airport,-26.696783,141.049092,328,NaN,Australia/Brisbane,AAB,AU,Tanbar,Queensland,Barcoo Shire,AP
2,AAC,HEAR,El Arish International Airport,31.074284,33.829172,85,NaN,Africa/Cairo,AAC,EG,Arish,Muhafazat Shamal Sina',NaN,AP
3,AAD,HCAD,Adado Airport,6.096286,46.637708,980,NaN,Africa/Khartoum,AAD,SO,Adado,NaN,NaN,AP
4,AAE,DABB,Les Salines Airport,36.821392,7.811857,36,NaN,Africa/Algiers,AAE,DZ,El Hadjar,Annaba,NaN,AP

In [6]:
new_df = df.dropna()
new_df

,code,icao,name,latitude,longitude,elevation,url,time_zone,city_code,country,city,state,county,type
11,AAL,EKYT,Aalborg Airport,57.086435,9.868076,19,http://www.aal.dk,Europe/Copenhagen,AAL,DK,Vadum,North Denmark,Alborg Kommune,AP
17,AAR,EKAH,Aarhus Airport,56.304543,10.612850,45,http://www.aar.dk/default.asp?id=87,Europe/Copenhagen,AAR,DK,Ebeltoft,Central Jutland,Syddjurs Kommune,AP
42,ABQ,KABQ,Albuquerque International Sunport,35.037669,-106.610968,5308,http://www.abqsunport.com/,America/Denver,ABQ,US,Albuquerque,New Mexico,Bernalillo County,AP
51,ABZ,EGPD,Aberdeen International Airport,57.201955,-2.201991,167,http://www.aberdeenairport.com/,Europe/London,ABZ,GB,Dyce,Scotland,Aberdeen City,AP
56,ACE,GCRR,Lanzarote Airport,28.945680,-13.607588,42,http://www.aena.es/en/lanzarote-airport/index....,Atlantic/Canary,ACE,ES,Tias,Canary Islands,Provincia de Las Palmas,AP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9630,YYB,CYYB,Jack Garland Airport,46.356823,-79.427250,1215,https://yyb.ca/,America/Toronto,YYB,CA,North Bay,Ontario,Nipissing District,AP
9737,ZLO,MMZO,Manzanillo Airport,19.113333,-104.350555,30,http://manzanillo.aeropuertosgap.com.mx/index....,America/Mexico_City,ZLO,MX,Manzanillo,Colima,Manzanillo,AP
9764,ZRH,LSZH,Zurich Airport,47.463549,8.553205,1416,http://www.zurich-airport.com/,Europe/Zurich,ZRH,CH,Glattbrugg / Rohr/Platten-Balsberg,Zurich,Bezirk Buelach,AP
9769,ZSE,FMEP,St Pierre dela Reunion,-21.333332,55.483334,59,http://www.grandsudreunion.org/FR2004/aeroport...,Indian/Reunion,ZSE,RE,Saint-Pierre,Reunion,Reunion,AP
9777,ZTH,LGZA,Zakinthos Airport,37.755833,20.888332,15,https://www.zth-airport.gr,Europe/Athens,ZTH,GR,Ambelokipoi,Ionian Islands,Nomos Zakynthou,AP